// ignore_for_file: unnecessary_string_escapes, equal_keys_in_map

import 'package:get/get.dart';

final class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          //NEW
          "Waste Bank Tool": "Waste Bank Tool",
          "Together for a Cleaner,": "Together for a Cleaner,",
          "Greener Future!": "Greener Future!",
          "Join our community-led initiative to help the planet.":
              "Join our community-led initiative to help the planet.",
          "Get Started": "Get Started",
          "Sign in": "Sign in",
          "Email": "Email",
          "Password": "Password",
          "Forgot Password?": "Forgot Password?",
          "Sign In": "Sign In",
          "Or": "Or",
          "Sign in with Google": "Sign in with Google",
          "Don’t have an account? Sign Up": "Don’t have an account? Sign Up",
          "Sign up": "Sign up",
          "Full Name": "Full Name",
          "Confirm Password": "Confirm Password",
          "Register": "Register",
          "Sign up with Google": "Sign up with Google",
          "Already part of the community? Sign in":
              "Already part of the community? Sign in",
          "Join the Waste Bank Community!": "Join the Waste Bank Community!",
          "Register your household or join as an admin to start making a difference.":
              "Register your household or join as an admin to start making a difference.",
          "House Number": "House Number",
          "Village": "Village",
          "Phone": "Phone",
          "Finish Registration": "Finish Registration",
          "Welcome to the ": "Welcome to the ",
          "Waste Bank Community!": "Waste Bank Community!",
          "Thank you for joining us on this eco-friendly journey!  Your account has been successfully registered.":
              "Thank you for joining us on this eco-friendly journey!  Your account has been successfully registered.",
          "Start the journey": "Start the journey",
          "Waste Bank Tool": "Waste Bank Tool",
          "Upcoming Events": "Upcoming Events",
          "Event": "Event",
          "Date": "Date",
          "Community Waste Bank Day": "Community Waste Bank Day",
          "Data Overview": "Data Overview",
          "Manage your Data": "Manage your Data",
          "Village and Household": "Village and Household",
          "Data Entry": "Data Entry",
          "Household Profiles": "Household Profiles",
          "All information added for the household":
              "All information added for the household",
          "Media Gallery": "Media Gallery",
          "A media gallery for photos, videos, and PDFs":
              "A media gallery for photos, videos, and PDFs",
          "Home": "Home",
          "Community": "Community",
          "Profile": "Profile",
          "Settings": "Settings",
          "Event Details": "Event Details",
          "Join Event": "Join Event",
          "Join Us and Make a": "Join Us and Make a",
          "Difference!": "Difference!",
          "Every role counts – let's build a greener tomorrow together!":
              "Every role counts – let's build a greener tomorrow together!",
          "Join as a User": "Join as a User",
          "Track your recyclables, earn rewards, and contribute to a cleaner community.":
              "Track your recyclables, earn rewards, and contribute to a cleaner community.",
          "Join as a Member": "Join as a Member",
          "Help organize, manage events, and lead the way toward sustainability.":
              "Help organize, manage events, and lead the way toward sustainability.",
          "Go next": "Go next",
          "Your Journey to a Cleaner Community":
              "Your Journey to a Cleaner Community",
          "Begins Now!": "Begins Now!",
          "Thank you for joining West Bank!":
              "Thank you for joining West Bank!",
          "Here’s what you can do next": "Here’s what you can do next",
          "Your Impact Starts": "Your Impact Starts",
          "Today!": "Today!",
          "Thank you for stepping up to drive change!":
              "Thank you for stepping up to drive change!",
          "NID Number": "NID Number",
          "Send request": "Send request",
          "Request": "Request",
          "Received!": "Received!",
          "Your request is under review by the admin. You'll receive a notification once it's approved.":
              "Your request is under review by the admin. You'll receive a notification once it's approved.",
          "Here’s what to expect next": "Here’s what to expect next",
          "Stay tuned!": "Stay tuned!",
          "Manage your Data": "Manage your Data",
          "Event Data": "Event Data",
          "Participations": "Participations",
          "App usage": "App usage",
          "Recycling data": "Recycling data",
          "Finance": "Finance",
          "All": "All",
          "Household participation": "Household participation",
          "homes": "homes",
          "Total Amount spent (baht)": "Total Amount spent (baht)",
          "Total Earning (baht)": "Total Earning (baht)",
          "Participation rate": "Participation rate",
          "Total Trash Collected (kg)": "Total Trash Collected (kg)",
          "kg": "kg",
          "Most common trash": "Most common trash",
          "Least common trash": "Least common trash",
          "Events": "Events",
          "location": "location",
          "comparison": "comparison",
          "Pause": "Pause",
          "New Household ": "New Household ",
          "Household parcentage": "Household parcentage",
          "Participation change": "Participation change",
          "Retention rate": "Retention rate",
          "Okay": "Okay",
          "Total users": "Total users",
          "New users": "New users",
          "Photos/Media": "Photos/Media",
          "Admin uses": "Admin uses",
          "Total recyclables (kg)": "Total recyclables (kg)",
          "Recycling Comparison (kg)": "Recycling Comparison (kg)",
          "Collection from villages": "Collection from villages",
          "Village": "Village",
          "Financial Impact": "Financial Impact",
          "Total Earnings": "Total Earnings",
          "Earnings comparison": "Earnings comparison",
          "Avg. Household Earnings": "Avg. Household Earnings",
          "Avg. Village Earnings": "Avg. Village Earnings",
          "Most Earned Village": "Most Earned Village",
          "Least Earned Village": "Least Earned Village",
          "Earnings Breakdown": "Earnings Breakdown",
          "Name": "Name",
          "Price/kg": "Price/kg",
          "Weight": "Weight",
          "Earnings": "Earnings",
          "Homes": "Homes",
          "Add Home": "Add Home",
          "Household Profiles": "Household Profiles",
          "Total Trash Collected": "Total Trash Collected",
          "Gallery": "Gallery",
          "Collectibles": "Collectibles",
          "Data Entry": "Data Entry",
          "Add Image": "Add Image",
          "House Name": "House Name",
          "House Number": "House Number",
          "Address": "Address",
          "Submit Info": "Submit Info",
          "Media Gallery": "Media Gallery",
          "West Bank Community": "West Bank Community",
          "Building Sustainability Together":
              "Building Sustainability Together",
          "Add Post": "Add Post",
          "Create post": "Create post",
          "Post": "Post",
          "Comment ...": "Comment ...",
          "Following": "Following",
          "Followers": "Followers",
          "Account Settings": "Account Settings",
          "Change password": "Change password",
          "Push notifications": "Push notifications",
          "Notifications": "Notifications",
          "More": "More",
          "About us": "About us",
          "Privacy policy": "Privacy policy",
          "Terms and conditions": "Terms and conditions",
          "We will send you the code in your mail.":
              "We will send you the code in your mail.",
          "Get code": "Get code",
          "Back": "Back",
          "Verify": "Verify",
          "Input OTP code here": "Input OTP code here",
          "Go next": "Go next",
          "Didn’t get code?": "RDidn’t get code?",
          "Send again.": "Send again.",
          "Save password": "Save password",
        },

        'th_TH': {
          //NEW
          "Waste Bank Tool": "เครื่องมือธนาคารขยะ",
          "Together for a Cleaner,": "ร่วมกันเพื่อความสะอาด,",
          "Greener Future!": "อนาคตที่เป็นมิตรกับสิ่งแวดล้อม!",
          "Join our community-led initiative to help the planet.":
              "เข้าร่วมโครงการที่นำโดยชุมชนของเราเพื่อช่วยโลกของเรา",
          "Get Started": "เริ่มต้น",
          "Sign in": "เข้าสู่ระบบ",
          "Email": "อีเมล",
          "Password": "รหัสผ่าน",
          "Forgot Password?": "ลืมรหัสผ่าน?",
          "Sign In": "เข้าสู่ระบบ",
          "Or": "หรือ",
          "Sign in with Google": "เข้าสู่ระบบด้วย Google",
          "Don’t have an account? Sign Up":
              "ยังไม่มีบัญชีใช่หรือไม่? สมัครสมาชิก",
          "Sign up": "สมัครสมาชิก",
          "Full Name": "ชื่อเต็ม",
          "Confirm Password": "ยืนยันรหัสผ่าน",
          "Register": "ลงทะเบียน",
          "Sign up with Google": "สมัครสมาชิกด้วย Google",
          "Already part of the community? Sign in":
              "เป็นส่วนหนึ่งของชุมชนแล้วหรือยัง? เข้าสู่ระบบ",
          "Join the Waste Bank Community!": "เข้าร่วมชุมชนธนาคารขยะ!",
          "Register your household or join as an admin to start making a difference.":
              "ลงทะเบียนบ้านของคุณหรือลงทะเบียนเป็นผู้ดูแลเพื่อเริ่มต้นสร้างความแตกต่าง",
          "House Number": "บ้านเลขที่",
          "Village": "หมู่บ้าน",
          "Phone": "โทรศัพท์",
          "Finish Registration": "เสร็จสิ้นการลงทะเบียน",
          "Welcome to the ": "ยินดีต้อนรับสู่ ",
          "Waste Bank Community!": "ชุมชนธนาคารขยะ!",
          "Thank you for joining us on this eco-friendly journey!  Your account has been successfully registered.":
              "ขอบคุณที่เข้าร่วมกับเราในเส้นทางที่เป็นมิตรกับสิ่งแวดล้อม! บัญชีของคุณได้รับการลงทะเบียนเรียบร้อยแล้ว",
          "Start the journey": "เริ่มการเดินทาง",
          "Upcoming Events": "กิจกรรมที่จะมาถึง",
          "Event": "กิจกรรม",
          "Date": "วันที่",
          "Community Waste Bank Day": "วันธนาคารขยะชุมชน",
          "Data Overview": "ภาพรวมข้อมูล",
          "Manage your Data": "จัดการข้อมูลของคุณ",
          "Village and Household": "หมู่บ้านและครัวเรือน",
          "Data Entry": "ป้อนข้อมูล",
          "Household Profiles": "โปรไฟล์ครัวเรือน",
          "All information added for the household":
              "ข้อมูลทั้งหมดที่เพิ่มสำหรับครัวเรือน",
          "Media Gallery": "แกลเลอรีสื่อ",
          "A media gallery for photos, videos, and PDFs":
              "แกลเลอรีสื่อสำหรับรูปภาพ วิดีโอ และ PDF",
          "Home": "หน้าหลัก",
          "Community": "ชุมชน",
          "Profile": "โปรไฟล์",
          "Settings": "การตั้งค่า",
          "Event Details": "รายละเอียดกิจกรรม",
          "Join Event": "เข้าร่วมกิจกรรม",
          "Join Us and Make a": "เข้าร่วมกับเราและสร้าง",
          "Difference!": "ความเปลี่ยนแปลง!",
          "Every role counts – let's build a greener tomorrow together!":
              "ทุกบทบาทมีความสำคัญ - มาร่วมสร้างอนาคตที่เขียวขจีด้วยกัน!",
          "Join as a User": "เข้าร่วมในฐานะผู้ใช้",
          "Track your recyclables, earn rewards, and contribute to a cleaner community.":
              "ติดตามการรีไซเคิลของคุณ รับรางวัล และมีส่วนร่วมในชุมชนที่สะอาดขึ้น",
          "Join as a Member": "เข้าร่วมในฐานะสมาชิก",
          "Help organize, manage events, and lead the way toward sustainability.":
              "ช่วยจัดการ กิจกรรม และนำทางไปสู่ความยั่งยืน",
          "Go next": "ไปต่อ",
          "Your Journey to a Cleaner Community":
              "การเดินทางของคุณสู่ชุมชนที่สะอาดขึ้น",
          "Begins Now!": "เริ่มต้นแล้ว!",
          "Thank you for joining West Bank!": "ขอบคุณที่เข้าร่วม West Bank!",
          "Here’s what you can do next": "นี่คือสิ่งที่คุณสามารถทำได้ต่อไป",
          "Your Impact Starts": "ผลกระทบของคุณเริ่มต้น",
          "Today!": "วันนี้!",
          "Thank you for stepping up to drive change!":
              "ขอบคุณที่ก้าวขึ้นมาสร้างการเปลี่ยนแปลง!",
          "NID Number": "หมายเลขบัตรประชาชน",
          "Send request": "ส่งคำขอ",
          "Request": "คำขอ",
          "Received!": "ได้รับแล้ว!",
          "Your request is under review by the admin. You'll receive a notification once it's approved.":
              "คำขอของคุณอยู่ในระหว่างการพิจารณาโดยผู้ดูแลระบบ คุณจะได้รับการแจ้งเตือนเมื่อได้รับการอนุมัติ",
          "Here’s what to expect next": "นี่คือสิ่งที่คุณคาดหวังต่อไป",
          "Stay tuned!": "ติดตาม!",
          "Event Data": "ข้อมูลกิจกรรม",
          "Participations": "การเข้าร่วม",
          "App usage": "การใช้งานแอป",
          "Recycling data": "ข้อมูลการรีไซเคิล",
          "Finance": "การเงิน",
          "All": "ทั้งหมด",
          "Household participation": "การเข้าร่วมของครัวเรือน",
          "homes": "บ้าน",
          "Total Amount spent (baht)": "ยอดใช้จ่ายทั้งหมด (บาท)",
          "Total Earning (baht)": "รายได้รวม (บาท)",
          "Participation rate": "อัตราการเข้าร่วม",
          "Total Trash Collected (kg)": "ขยะที่เก็บทั้งหมด (กก.)",
          "kg": "กก.",
          "Most common trash": "ขยะที่พบบ่อยที่สุด",
          "Least common trash": "ขยะที่พบน้อยที่สุด",
          "Events": "กิจกรรม",
          "location": "สถานที่",
          "comparison": "การเปรียบเทียบ",
          "Pause": "หยุดชั่วคราว",
          "New Household ": "บ้านใหม่",
          "Household parcentage": "เปอร์เซ็นต์ครัวเรือน",
          "Participation change": "การเปลี่ยนแปลงการเข้าร่วม",
          "Retention rate": "อัตราการรักษา",
          "Okay": "ตกลง",
          "Total users": "ผู้ใช้ทั้งหมด",
          "New users": "ผู้ใช้ใหม่",
          "Photos/Media": "รูปภาพ/สื่อ",
          "Admin uses": "การใช้งานของผู้ดูแล",
          "Total recyclables (kg)": "รีไซเคิลทั้งหมด (กก.)",
          "Recycling Comparison (kg)": "การเปรียบเทียบการรีไซเคิล (กก.)",
          "Collection from villages": "การเก็บรวบรวมจากหมู่บ้าน",
          "Village": "หมู่บ้าน",
          "Financial Impact": "ผลกระทบทางการเงิน",
          "Total Earnings": "รายได้ทั้งหมด",
          "Earnings comparison": "การเปรียบเทียบรายได้",
          "Avg. Household Earnings": "รายได้เฉลี่ยของครัวเรือน",
          "Avg. Village Earnings": "รายได้เฉลี่ยของหมู่บ้าน",
          "Most Earned Village": "หมู่บ้านที่ได้รับรายได้มากที่สุด",
          "Least Earned Village": "หมู่บ้านที่ได้รับรายได้น้อยที่สุด",
          "Earnings Breakdown": "การแยกรายได้",
          "Name": "ชื่อ",
          "Price/kg": "ราคา/กก.",
          "Weight": "น้ำหนัก",
          "Earnings": "รายได้",
          "Homes": "บ้าน",
          "Add Home": "เพิ่มบ้าน",
          "Household Profiles": "โปรไฟล์ครัวเรือน",
          "Total Trash Collected": "ขยะที่เก็บทั้งหมด",
          "Gallery": "แกลเลอรี",
          "Collectibles": "ของสะสม",
          "Data Entry": "ป้อนข้อมูล",
          "Add Image": "เพิ่มรูปภาพ",
          "House Name": "ชื่อบ้าน",
          "House Number": "บ้านเลขที่",
          "Address": "ที่อยู่",
          "Submit Info": "ส่งข้อมูล",
          "Media Gallery": "แกลเลอรีสื่อ",
          "West Bank Community": "ชุมชน West Bank",
          "Building Sustainability Together": "สร้างความยั่งยืนร่วมกัน",
          "Add Post": "เพิ่มโพสต์",
          "Create post": "สร้างโพสต์",
          "Post": "โพสต์",
          "Comment ...": "แสดงความคิดเห็น ...",
          "Following": "กำลังติดตาม",
          "Followers": "ผู้ติดตาม",
          "Account Settings": "การตั้งค่าบัญชี",
          "Change password": "เปลี่ยนรหัสผ่าน",
          "Push notifications": "การแจ้งเตือนแบบพุช",
          "Notifications": "การแจ้งเตือน",
          "More": "เพิ่มเติม",
          "About us": "เกี่ยวกับเรา",
          "Privacy policy": "นโยบายความเป็นส่วนตัว",
          "Terms and conditions": "ข้อกำหนดและเงื่อนไข",
          "We will send you the code in your mail.":
              "เราจะส่งรหัสให้คุณทางอีเมล",
          "Get code": "รับรหัส",
          "Back": "ย้อนกลับ",
          "Verify": "ยืนยัน",
          "Input OTP code here": "ป้อนรหัส OTP ที่นี่",
          "Go next": "ไปต่อ",
          "Didn’t get code?": "ไม่ได้รับรหัส?",
          "Send again.": "ส่งอีกครั้ง",
          "Save password": "บันทึกรหัสผ่าน"
        }
      };
}
